# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FaceRegconition(object):
    def setupUi(self, FaceRegconition):
        FaceRegconition.setObjectName("FaceRegconition")
        FaceRegconition.resize(464, 270)
        self.gridLayoutWidget = QtWidgets.QWidget(FaceRegconition)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(310, 50, 141, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.nameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.nameLabel.setText("")
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout.addWidget(self.nameLabel)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.date = QtWidgets.QLabel(self.gridLayoutWidget)
        self.date.setObjectName("date")
        self.horizontalLayout_2.addWidget(self.date)
        self.dateLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dateLabel.setText("")
        self.dateLabel.setObjectName("dateLabel")
        self.horizontalLayout_2.addWidget(self.dateLabel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.time = QtWidgets.QLabel(self.gridLayoutWidget)
        self.time.setObjectName("time")
        self.horizontalLayout_3.addWidget(self.time)
        self.timeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.timeLabel.setText("")
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout_3.addWidget(self.timeLabel)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.totalTime = QtWidgets.QLabel(self.gridLayoutWidget)
        self.totalTime.setObjectName("totalTime")
        self.horizontalLayout_4.addWidget(self.totalTime)
        self.totalTimeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.totalTimeLabel.setText("")
        self.totalTimeLabel.setObjectName("totalTimeLabel")
        self.horizontalLayout_4.addWidget(self.totalTimeLabel)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(FaceRegconition)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 271, 221))
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Zilla Slab")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")

        self.retranslateUi(FaceRegconition)
        QtCore.QMetaObject.connectSlotsByName(FaceRegconition)

    def retranslateUi(self, FaceRegconition):
        _translate = QtCore.QCoreApplication.translate
        FaceRegconition.setWindowTitle(_translate("FaceRegconition", "Dialog"))
        self.name.setText(_translate("FaceRegconition", "Name:"))
        self.date.setText(_translate("FaceRegconition", "Date:"))
        self.time.setText(_translate("FaceRegconition", "Time:"))
        self.totalTime.setText(_translate("FaceRegconition", "Total time:"))
        self.groupBox.setTitle(_translate("FaceRegconition", "Face Regconition"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FaceRegconition = QtWidgets.QDialog()
    ui = Ui_FaceRegconition()
    ui.setupUi(FaceRegconition)
    FaceRegconition.show()
    sys.exit(app.exec_())
