# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'information.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Information(object):
    def setupUi(self, Information):
        Information.setObjectName("Information")
        Information.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Information)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(160, 210, 160, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.information = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.information.setContentsMargins(0, 0, 0, 0)
        self.information.setObjectName("information")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.nameLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.nameLabel.setText("")
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout.addWidget(self.nameLabel)
        self.information.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.id = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.id.setObjectName("id")
        self.horizontalLayout_4.addWidget(self.id)
        self.idLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.idLabel.setText("")
        self.idLabel.setObjectName("idLabel")
        self.horizontalLayout_4.addWidget(self.idLabel)
        self.information.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.timeIn = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.timeIn.setObjectName("timeIn")
        self.horizontalLayout_2.addWidget(self.timeIn)
        self.timeInLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.timeInLabel.setText("")
        self.timeInLabel.setObjectName("timeInLabel")
        self.horizontalLayout_2.addWidget(self.timeInLabel)
        self.information.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(180, 70, 121, 131))
        self.imageLabel.setObjectName("imageLabel")
        Information.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Information)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        Information.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Information)
        self.statusbar.setObjectName("statusbar")
        Information.setStatusBar(self.statusbar)

        self.retranslateUi(Information)
        QtCore.QMetaObject.connectSlotsByName(Information)

    def retranslateUi(self, Information):
        _translate = QtCore.QCoreApplication.translate
        Information.setWindowTitle(_translate("Information", "Information"))
        self.name.setText(_translate("Information", "Name"))
        self.id.setText(_translate("Information", "Student ID"))
        self.timeIn.setText(_translate("Information", "Time-in"))
        self.imageLabel.setText(_translate("Information", "image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Information = QtWidgets.QMainWindow()
    ui = Ui_Information()
    ui.setupUi(Information)
    Information.show()
    sys.exit(app.exec_())
